### ISSUE TITLE
재배포 가능한 폰트로의 대체

### ISSUE THREAD

**Issue by euler0** [s2quake/JSSoft.Font#1]
Fonts 폴더에 포함된 SF Mono나 Gulim 폰트의 원본 파일(otf, ttc)은 재배포 가능한 파일이 아니기 때문에, 삭제하거나 재배포 가능한 라이선스(SIL OFL*)의 폰트로 대체하는 것이 좋을 것 같습니다.

(나눔고딕같은 무료 공개된 폰트는 대부분 SIL OFL 폰트입니다.)

* [SIL OFL](https://ko.wikipedia.org/wiki/SIL_오픈_폰트_라이선스)

**Comment by s2quake** [comment]
넵
